#!/usr/bin/env python

# This script generates an SVG file from a text file with
# given coordinates for a NACA airfoil profile.
#
# Sample data can be found here:
#
# http://www.pdas.com/naca456samples.html
#
# Anders Logg, 2009-10-06

import sys

# Get filename
if not len(sys.argv) == 2:
    print "Usage naca2svg nacadata.txt"
    sys.exit(1)
filename = sys.argv[1]

# Read coordinates
print "Reading data from", filename
lines = open(filename).read().split("INTERPOLATED COORDINATES")[1].split("End")[0].split("ylower")[1].split("\n")
lines = [line.strip() for line in lines]
lines = [line for line in lines if len(line) > 0]
upper = []
lower = []
for line in lines:
    i, x, yupper, ylower = line.split()
    upper.append((float(x), float(yupper)))
    lower.append((float(x), float(ylower)))
lower.reverse()
coordinates = upper + lower[1:]

for c in coordinates:
    print c

# Scale coordinates
L = 1000
for (i, (x, y)) in enumerate(coordinates):

    x = 0.1*L + 0.8*L*x
    y = 0.5*L - 0.8*L*y

    coordinates[i] = (x, y)

# Write SVG file
template = """\
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="%g" height="%g">
  <g>
    <path
       style="fill:none;fill-rule:evenodd;stroke:#000000;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       d="M %s z"/>
  </g>
</svg>
"""
filename = filename.split(".")[0] + ".svg"
print "Writing SVG file to", filename
file = open(filename, "w")
file.write(template % (L, L, " L ".join("%g %g" % xy for xy in coordinates)))
