#!/usr/bin/env python
#
# Strip file from environments that shouldn't be spell-checked
# Anders Logg, 2010-12-16

import sys

text = sys.stdin.read()

environments = ["c++", "python", "bash"]

for environment in environments:
    if not environment in text:
        print "nope"
        continue
    parts = text.split("\\begin{%s}" % environment)
    text = parts[0]
    for part in parts[1:]:
        text += part.split("\\end{%s}" % environment)[1]

print text
