#!/usr/bin/env python
#
# Strip file from stuff that shouldn't be spell-checked.
#
# Anders Logg, 2010-12-16

import sys

text = sys.stdin.read()

environments = [("\\begin{c++}",        "\\end{c++}"),
                ("\\begin{python}",     "\\end{python}"),
                ("\\begin{bash}",       "\\end{bash}"),
                ("\\begin{align}",      "\\end{align}"),
                ("\\begin{align}",      "\\end{align}"),
                ("\\emp{",              "}"),
                ("\\texttt{",           "}"),
                ("\\citep{",            "}"),
                ("\\citet{",            "}"),
                ("\\ref{",              "}"),
                ("\\eqref{",            "}"),
                ("\\label{",            "}"),
                ("\\import{",           ".pdf_tex}"),
                ("\\includegraphics",   ".pdf}"),
                ("\\includegraphics",   ".png}"),
                ("%",                   "\n"),
                ("%",                   "\n")]

for begin, end in environments:
    if not begin in text:
        continue
    parts = text.split(begin)
    text = parts[0]
    for part in parts[1:]:
        subparts = part.split(end)
        text += end.join(subparts[1:])

print text
